Update dropcheck

diff --git a/dropcheck b/dropcheck
--- a/dropcheck
+++ b/dropcheck
@@ -64,6 +64,46 @@ get_ipv4_gw_addr () {
   return 0
 }
 
+get_ipv6_cidr () {
+  if [ $# != 1 ]; then
+    return 1
+  fi
+  local cidr=$(ip -6 addr show ${1} | grep 'inet6' | grep -v 'fe80' | head -n 1 | awk '{print $2}')
+  if [ -z "{$cidr}" ]; then
+    return 1
+  fi
+  echo "${cidr}"
+  return 0
+}
+
+get_ipv6_addr () {
+  if [ $# != 1 ]; then
+    return 1
+  fi
+  cidr=$(get_ipv6_cidr ${1})
+  if [ $? != 0 ]; then
+    return 1
+  fi
+  addr=$(echo ${cidr} | cut -d '/' -f 1)
+  if [ -z "${addr}" ]; then
+    return 1
+  fi
+  echo "${addr}"
+  return 0
+}
+
+get_ipv6_gw_addr () {
+  if [ $# != 1 ]; then
+    return 1
+  fi
+  local gw_addr=$(ip -6 route | grep -m 1 "default.*${1}" | awk '{print $3}' | cut -d '%' -f 1)
+  if [ -z "{$gw_addr}" ]; then
+    return 1
+  fi
+  echo "${gw_addr}"
+  return 0
+}
+
 print_status () {
   if [ $# != 1 ]; then
     return 1
@@ -91,20 +131,41 @@ test_ipv4 () {
   if [ $ret != 0 ]; then
     echo 'Unable to retrieve IPv4 address'
   else
-    echo "IPv4 address: ${ipv4_cidr}, gateway address: ${ipv4_gw_addr}"
+    echo "IPv4 address: ${ipv4_cidr} (default gateway: ${ipv4_gw_addr})"
+  fi
+  return $ret
+}
+
+test_ipv6 () {
+  if [ $# != 1 ]; then
+    return 1
+  fi
+  local ret=0
+  local ipv6_cidr
+  ipv6_cidr=$(get_ipv6_cidr ${if_name})
+  ret=$((${ret} || ${?}))
+  local ipv6_gw_addr
+  ipv6_gw_addr=$(get_ipv6_gw_addr ${if_name})
+  ret=$((${ret} || ${?}))
+  print_status $ret
+  if [ $ret != 0 ]; then
+    echo 'Unable to retrieve IPv6 address'
+  else
+    echo "IPv6 address: ${ipv6_cidr} (default gateway: ${ipv6_gw_addr})"
   fi
   return $ret
 }
 
 test_ping_ipv4 () {
   local res
+  source_addr=$(get_ipv4_addr ${2})
   case $# in
-    1 )
-      res=$(ping -c ${PING_COUNT} -i ${PING_INTERVAL} ${1})
-      ;;
     2 )
-      local size=$((${2} - 28))
-      res=$(ping -c ${PING_COUNT} -i ${PING_INTERVAL} -s ${size} ${1})
+      res=$(ping -c ${PING_COUNT} -i ${PING_INTERVAL} -S ${source_addr} ${1})
+      ;;
+    3 )
+      local size=$((${3} - 28))
+      res=$(ping -c ${PING_COUNT} -i ${PING_INTERVAL} -s ${size} -S ${source_addr} ${1})
       ;;
     * )
       return 1
@@ -113,11 +174,11 @@ test_ping_ipv4 () {
   local ret=$?
   print_status $ret
   case $# in
-    1 )
+    2 )
       echo -n "ping ${1}: "
       ;;
-    2 )
-      echo -n "ping ${1} (${2} bytes): "
+    3 )
+      echo -n "ping ${1} (${3} bytes): "
       ;;
     * )
       return 1
@@ -131,42 +192,62 @@ test_ping_ipv4 () {
   return $ret
 }
 
-test_dig_v4 () {
-  if [ $# != 1 ]; then
+test_ping_ipv6 () {
+  local res
+  case $# in
+    2 )
+      res=$(ping6 -c ${PING_COUNT} -i ${PING_INTERVAL} -I ${2} ${1})
+      ;;
+    3 )
+      local size=$((${3} - 48))
+      res=$(ping6 -c ${PING_COUNT} -i ${PING_INTERVAL} -s ${size} -I ${2} ${1})
+      ;;
+    * )
+      return 1
+      ;;
+  esac
+  local ret=$?
+  print_status $ret
+  case $# in
+    2 )
+      echo -n "ping ${1}: "
+      ;;
+    3 )
+      echo -n "ping ${1} (${3} bytes): "
+      ;;
+    * )
+      return 1
+      ;;
+  esac
+  if [ $ret != 0 ]; then
+    echo $(echo "${res}" | tail -n 1)
+  else
+    echo $(echo "${res}" | tail -n 2 | head -n 1)
+  fi
+  return $ret
+}
+
+test_dig () {
+  if [ $# != 2 ]; then
     return 1
   fi
   local res
-  res=$(dig +short $1 A | grep -v -e '^$')
+  res=$(dig +short $1 $2 | grep -v -e '^$')
   local ret=$?
   print_status $ret
   if [ $ret != 0 ]; then
-    echo "dig ${1} A"
+    echo "dig ${1} ${2}"
   else
-    echo "${1} IN A ${res}"
+    echo "${1} IN ${2} ${res}"
   fi
 }
 
-test_dig_v6 () {
+test_http () {
   if [ $# != 1 ]; then
     return 1
   fi
   local res
-  res=$(dig +short $1 AAAA | grep -v -e '^$')
-  local ret=$?
-  print_status $ret
-  if [ $ret != 0 ]; then
-    echo "dig ${1} AAAA"
-  else
-    echo "${1} IN AAAA ${res}"
-  fi
-}
-
-test_http_v4 () {
-  if [ $# != 1 ]; then
-    return 1
-  fi
-  local res
-  res=$(wget --page-requisites -O .dropcheck $1 2>&1 | grep '200 OK')
+  res=$(wget -p -T 3 -O .dropcheck $1 2>&1 | grep '200 OK')
   local ret=$?
   print_status $ret
   echo -n "GET $1"
@@ -183,20 +264,30 @@ main () {
   if_name=$1
 
   test_ipv4 $if_name
+  test_ipv6 $if_name
 
   ipv4_addr=$(get_ipv4_addr ${if_name})
   ipv4_gw_addr=$(get_ipv4_gw_addr ${if_name})
+  ipv6_addr=$(get_ipv6_addr ${if_name})
+  ipv6_gw_addr=$(get_ipv6_gw_addr ${if_name})
 
-  test_ping_ipv4 $ipv4_gw_addr
-  test_ping_ipv4 $ipv4_gw_addr 1500
-  test_ping_ipv4 $GOOGLE_PUBLIC_DNS_V4
-  test_ping_ipv4 $GOOGLE_PUBLIC_DNS_V4 1500
+  test_ping_ipv4 $ipv4_gw_addr $if_name
+  test_ping_ipv4 $ipv4_gw_addr $if_name 1500
+  test_ping_ipv4 $GOOGLE_PUBLIC_DNS_V4 $if_name
+  test_ping_ipv4 $GOOGLE_PUBLIC_DNS_V4 $if_name 1500
 
-  test_dig_v4 $WIDE_DOMAIN
-  test_dig_v6 $WIDE_DOMAIN
+  test_ping_ipv6 $ipv6_gw_addr $if_name
+  test_ping_ipv6 $ipv6_gw_addr $if_name 1280
+  test_ping_ipv6 $GOOGLE_PUBLIC_DNS_V6 $if_name
+  test_ping_ipv6 $GOOGLE_PUBLIC_DNS_V6 $if_name 1280
 
-  test_http_v4 $GOOGLE_IPV4
-  test_http_v4 $GOOGLE_IPV6
+  test_dig $WIDE_DOMAIN A
+  test_dig $WIDE_DOMAIN AAAA
+
+  test_http $GOOGLE_IPV4
+  test_http $GOOGLE_IPV6
+
+  rm -rf .dropcheck
 }
 
 if [ $# != 1 ]; then
