Update dropcheck

diff --git a/dropcheck b/dropcheck
--- a/dropcheck
+++ b/dropcheck
@@ -9,8 +9,10 @@ BANNER="
                                               (c) 2018 sira
 "
 
-IPV4_RE='([0-9]{1,3}\.){3}[0-9]{1,3}'
-IPV6_RE='([0-9a-fA-F:]+:+)+[0-9a-fA-F]+'
+IPV4_CIDR_RE='([0-9]{1,3}\.){3}[0-9]{1,3}\/([0-9]|[12][0-9]|3[0-2])'
+IPV6_CIDR_RE='([0-9a-fA-F:]+:+)+[0-9a-fA-F]+\/([0-9]|[1-8][0-9]|9[0-9]|1[01][0-9]|12[0-8])'
+IPV4_ADDR_RE='([0-9]{1,3}\.){3}[0-9]{1,3}'
+IPV6_ADDR_RE='([0-9a-fA-F:]+:+)+[0-9a-fA-F]+'
 
 PING_INTERVAL=0.1
 PING_COUNT=10
@@ -29,7 +31,8 @@ get_ipv4_cidr () {
     return 1
   fi
   local cidr=$(ip -4 addr show ${1} | grep -m 1 'inet' | awk '{print $2}')
-  if [ -z "${cidr}" ]; then
+  echo "$cidr" | grep -E $IPV4_CIDR_RE > /dev/null
+  if [ $? != 0 ]; then
     return 1
   fi
   echo "${cidr}"
@@ -40,12 +43,15 @@ get_ipv4_addr () {
   if [ $# != 1 ]; then
     return 1
   fi
+  local cidr
   cidr=$(get_ipv4_cidr ${1})
   if [ $? != 0 ]; then
     return 1
   fi
+  local addr
   addr=$(echo ${cidr} | cut -d '/' -f 1)
-  if [ -z "${addr}" ]; then
+  echo $addr | grep -E $IPV4_ADDR_RE > /dev/null
+  if [ $? != 0 ]; then
     return 1
   fi
   echo "${addr}"
@@ -57,7 +63,8 @@ get_ipv4_gw_addr () {
     return 1
   fi
   local gw_addr=$(ip -4 route | grep -m 1 "default.*${1}" | awk '{print $3}')
-  if [ -z "{$gw_addr}" ]; then
+  echo $gw_addr | grep -E $IPV4_ADDR_RE > /dev/null
+  if [ $? != 0 ]; then
     return 1
   fi
   echo "${gw_addr}"
@@ -69,7 +76,8 @@ get_ipv6_cidr () {
     return 1
   fi
   local cidr=$(ip -6 addr show ${1} | grep 'inet6' | grep -v 'fe80' | head -n 1 | awk '{print $2}')
-  if [ -z "{$cidr}" ]; then
+  echo $cidr | grep -E $IPV6_CIDR_RE > /dev/null
+  if [ $? != 0 ]; then
     return 1
   fi
   echo "${cidr}"
@@ -80,12 +88,15 @@ get_ipv6_addr () {
   if [ $# != 1 ]; then
     return 1
   fi
+  local cidr
   cidr=$(get_ipv6_cidr ${1})
   if [ $? != 0 ]; then
     return 1
   fi
+  local addr
   addr=$(echo ${cidr} | cut -d '/' -f 1)
-  if [ -z "${addr}" ]; then
+  echo $addr | grep -E $IPV6_ADDR_RE > /dev/null
+  if [ $? != 0 ]; then
     return 1
   fi
   echo "${addr}"
@@ -97,14 +108,15 @@ get_ipv6_gw_addr () {
     return 1
   fi
   local gw_addr=$(ip -6 route | grep -m 1 "default.*${1}" | awk '{print $3}' | cut -d '%' -f 1)
-  if [ -z "{$gw_addr}" ]; then
+  echo $gw_addr | grep -E $IPV6_ADDR_RE > /dev/null
+  if [ $? != 0 ]; then
     return 1
   fi
   echo "${gw_addr}"
   return 0
 }
 
-print_status () {
+echo_test_status () {
   if [ $# != 1 ]; then
     return 1
   fi
@@ -113,6 +125,14 @@ print_status () {
   else
     echo -ne "[\e[32;1mPASS\e[m] "
   fi
+  return 0
+}
+
+echo_bold () {
+  if [ $# != 1 ]; then
+    return 1
+  fi
+  echo -e "\e[1m${1}\e[m"
   return 0
 }
 
@@ -127,7 +147,7 @@ test_ipv4 () {
   local ipv4_gw_addr
   ipv4_gw_addr=$(get_ipv4_gw_addr ${if_name})
   ret=$((${ret} || ${?}))
-  print_status $ret
+  echo_test_status $ret
   if [ $ret != 0 ]; then
     echo 'Unable to retrieve IPv4 address'
   else
@@ -147,7 +167,7 @@ test_ipv6 () {
   local ipv6_gw_addr
   ipv6_gw_addr=$(get_ipv6_gw_addr ${if_name})
   ret=$((${ret} || ${?}))
-  print_status $ret
+  echo_test_status $ret
   if [ $ret != 0 ]; then
     echo 'Unable to retrieve IPv6 address'
   else
@@ -172,7 +192,7 @@ test_ping_ipv4 () {
       ;;
   esac
   local ret=$?
-  print_status $ret
+  echo_test_status $ret
   case $# in
     2 )
       echo -n "ping ${1}: "
@@ -207,7 +227,7 @@ test_ping_ipv6 () {
       ;;
   esac
   local ret=$?
-  print_status $ret
+  echo_test_status $ret
   case $# in
     2 )
       echo -n "ping ${1}: "
@@ -234,7 +254,7 @@ test_dig () {
   local res
   res=$(dig +short $1 $2 | grep -v -e '^$')
   local ret=$?
-  print_status $ret
+  echo_test_status $ret
   if [ $ret != 0 ]; then
     echo "dig ${1} ${2}"
   else
@@ -249,7 +269,7 @@ test_http () {
   local res
   res=$(wget -p -T 3 -O .dropcheck $1 2>&1 | grep '200 OK')
   local ret=$?
-  print_status $ret
+  echo_test_status $ret
   echo -n "GET $1"
   if [ $ret != 0 ]; then
     echo
@@ -261,32 +281,53 @@ test_http () {
 
 main () {
   echo "${BANNER}"
+
   if_name=$1
 
+  echo_bold 'STEP 1. retrieve IP addresses'
   test_ipv4 $if_name
+  check_ipv4=$?
   test_ipv6 $if_name
+  check_ipv6=$?
+  if [ $check_ipv4 != 0 ] && [ $check_ipv6 != 0 ]; then
+    echo_bold "Unable to retrieve IP address(es)."
+    echo_bold "Check the DHCP server or set IP address(es) by your self."
+    echo
+    exit 1
+  fi
+  echo
 
-  ipv4_addr=$(get_ipv4_addr ${if_name})
-  ipv4_gw_addr=$(get_ipv4_gw_addr ${if_name})
-  ipv6_addr=$(get_ipv6_addr ${if_name})
-  ipv6_gw_addr=$(get_ipv6_gw_addr ${if_name})
+  echo_bold 'STEP 2. ping'
+  if [ $check_ipv4 = 0 ]; then
+    ipv4_addr=$(get_ipv4_addr ${if_name})
+    ipv4_gw_addr=$(get_ipv4_gw_addr ${if_name})
+    test_ping_ipv4 $ipv4_gw_addr $if_name
+    test_ping_ipv4 $ipv4_gw_addr $if_name 1500
+    test_ping_ipv4 $GOOGLE_PUBLIC_DNS_V4 $if_name
+    test_ping_ipv4 $GOOGLE_PUBLIC_DNS_V4 $if_name 1500
+  fi
+  if [ $check_ipv6 = 0 ]; then
+    ipv6_addr=$(get_ipv6_addr ${if_name})
+    ipv6_gw_addr=$(get_ipv6_gw_addr ${if_name})
+    test_ping_ipv6 $ipv6_gw_addr $if_name
+    test_ping_ipv6 $ipv6_gw_addr $if_name 1280
+    test_ping_ipv6 $GOOGLE_PUBLIC_DNS_V6 $if_name
+    test_ping_ipv6 $GOOGLE_PUBLIC_DNS_V6 $if_name 1280
+  fi
+  echo
 
-  test_ping_ipv4 $ipv4_gw_addr $if_name
-  test_ping_ipv4 $ipv4_gw_addr $if_name 1500
-  test_ping_ipv4 $GOOGLE_PUBLIC_DNS_V4 $if_name
-  test_ping_ipv4 $GOOGLE_PUBLIC_DNS_V4 $if_name 1500
-
-  test_ping_ipv6 $ipv6_gw_addr $if_name
-  test_ping_ipv6 $ipv6_gw_addr $if_name 1280
-  test_ping_ipv6 $GOOGLE_PUBLIC_DNS_V6 $if_name
-  test_ping_ipv6 $GOOGLE_PUBLIC_DNS_V6 $if_name 1280
-
+  echo_bold 'STEP 3. DNS and HTTP'
   test_dig $WIDE_DOMAIN A
   test_dig $WIDE_DOMAIN AAAA
+  if [ $check_ipv4 = 0 ]; then
+    test_http $GOOGLE_IPV4
+  fi
+  if [ $check_ipv6 = 0 ]; then
+    test_http $GOOGLE_IPV6
+  fi
+  echo
 
-  test_http $GOOGLE_IPV4
-  test_http $GOOGLE_IPV6
-
+  # Cleanup
   rm -rf .dropcheck
 }
 
